/* eslint-disable @typescript-eslint/no-require-imports */
import {Images} from './types';

const Assets: Images = {
  google: require('../assets/google.png'),
  facebook: require('../assets/facebook.png'),
  questionMark: require('../assets/questionMark.png'),
  back: require('../assets/left-arrow.png'),
  avatar: require('../assets/avatar.png'),
  menu: require('../assets/menu.png'),
  search: require('../assets/search.png'),
  filter: require('../assets/filter.png'),
  heart: require('../assets/heart.png'),
  heartUnfilled: require('../assets/heart-outline.png'),
  basket: require('../assets/basket.png'),
  star: require('../assets/star.png'),
  sunglasses: require('../assets/GucciSunglases.png'),
  whiteDress: require('../assets/whitedress.png'),
  redDress: require('../assets/reddress.png'),
  bin: require('../assets/bin.png'),
  check: require('../assets/check.png'),
  oval: require('../assets/oval.png'),
  wallet: require('../assets/wallet.png'),
  card: require('../assets/card.png'),
  paypal: require('../assets/paypal.png'),
  credit: require('../assets/credit-card.png'),
  amex: require('../assets/amex.png'),
  visa: require('../assets/visa.png'),
  mastercard: require('../assets/master-card.png'),
  jcb: require('../assets/jcb.png'),
  unionpay: require('../assets/unionpay.png'),
  discover: require('../assets/discover.png'),
  dinners: require('../assets/dinners-club.png'),
  maestro: require('../assets/maestro.png'),
  trackOrder: require('../assets/Trackorder.png'),
  products: require('../assets/products.png'),
  collection: require('../assets/collection.png'),
  category: require('../assets/category.png'),
  home: require('../assets/home.png'),
  catalog: require('../assets/catalog.png'),
  gps: require('../assets/gps.png'),
  truecaller: require('../assets/truecaller.png'),
};

export default Assets;
